"""Vocabulary tables and Ghost tag aliases for :mod:`pesacheck.tags`.

Split out of ``tags.py`` the way ``language_markers.py`` is split out of
``language.py``: the logic there is short and the data here is long, and they
change for entirely different reasons.

Two kinds of thing live here, and the distinction matters.

**The ``*_BY_QCODE`` tables are transcribed, not authored.** Each mirrors one
vocabulary in the tracked content config under ``server/data/vocabularies/`` --
the reviewed JSON that ``app:initialize_data`` seeds over the ``vocabularies``
collection. Editing a tracked vocabulary can leave these tables stale without any
change here. ``tests/test_tags.py``
asserts every qcode and display name below still matches the dump; that test is
the only thing standing between a dump refresh and a corpus of items carrying
labels the client cannot resolve. Regenerate rather than hand-edit.

**The ``*_ALIASES`` tables are the actual editorial judgement.** Ghost tags were
authored years before these vocabularies existed and by different people, so the
tag text and the vocabulary label frequently disagree -- ``Ivory Coast`` for
``Côte d'Ivoire``, ``Swahili`` for ``Kiswahili``, ``Twitter`` for ``X/Twitter``,
``Short Form`` for ``Quick Read``. Alias keys are written in their normalised
form (see :func:`pesacheck.tags.normalise_tag`), which is why they look
punctuation-free and lower-case.

Deliberately *not* aliased, and left to fall through to ``keywords``:

- ``Vaccines`` -- the ``Harm_type`` vocabulary offers ``Anti-vaxx`` and
  ``Health``, and choosing between them asserts something about the claim that
  the tag does not say. An editor's call, not a mapping's.
- ``Horn Of Africa``, ``Amhara``, ``Tigray``, ``Nairobi``, ``Kampala`` and the
  other sub- and supra-national places -- ``countries`` is a country list, and
  the ``regions`` vocabulary these belong in is not on the Article profile.
- Every person, organisation and event name. There is no vocabulary for them.
"""

COUNTRIES = {
    "AFG": "Afghanistan",
    "ALA": "Aland Islands",
    "ALB": "Albania",
    "DZA": "Algeria",
    "ASM": "American Samoa",
    "AND": "Andorra",
    "AGO": "Angola",
    "AIA": "Anguilla",
    "ATA": "Antarctica",
    "ATG": "Antigua and Barbuda",
    "ARG": "Argentina",
    "ARM": "Armenia",
    "ABW": "Aruba",
    "AUS": "Australia",
    "AUT": "Austria",
    "AZE": "Azerbaijan",
    "BHS": "Bahamas",
    "BHR": "Bahrain",
    "BGD": "Bangladesh",
    "BRB": "Barbados",
    "BLR": "Belarus",
    "BEL": "Belgium",
    "BLZ": "Belize",
    "BEN": "Benin",
    "BMU": "Bermuda",
    "BTN": "Bhutan",
    "BOL": "Bolivia",
    "BIH": "Bosnia and Herzegovina",
    "BWA": "Botswana",
    "BVT": "Bouvet Island",
    "BRA": "Brazil",
    "IOT": "British Indian Ocean Territory",
    "VGB": "British Virgin Islands",
    "BRN": "Brunei Darussalam",
    "BGR": "Bulgaria",
    "BFA": "Burkina Faso",
    "BDI": "Burundi",
    "KHM": "Cambodia",
    "CMR": "Cameroon",
    "CAN": "Canada",
    "CPV": "Cape Verde",
    "CYM": "Cayman Islands",
    "CAF": "Central African Republic",
    "TCD": "Chad",
    "CHL": "Chile",
    "CHN": "China",
    "CXR": "Christmas Island",
    "CCK": "Cocos (Keeling) Islands",
    "COL": "Colombia",
    "COM": "Comoros",
    "COG": "Congo (Brazzaville)",
    "COD": "Congo, (Kinshasa)",
    "COK": "Cook Islands",
    "CRI": "Costa Rica",
    "HRV": "Croatia",
    "CUB": "Cuba",
    "CYP": "Cyprus",
    "CZE": "Czech Republic",
    "CIV": "Côte d'Ivoire",
    "DNK": "Denmark",
    "DJI": "Djibouti",
    "DMA": "Dominica",
    "DOM": "Dominican Republic",
    "ECU": "Ecuador",
    "EGY": "Egypt",
    "SLV": "El Salvador",
    "GNQ": "Equatorial Guinea",
    "ERI": "Eritrea",
    "EST": "Estonia",
    "ETH": "Ethiopia",
    "FLK": "Falkland Islands (Malvinas)",
    "FRO": "Faroe Islands",
    "FJI": "Fiji",
    "FIN": "Finland",
    "FRA": "France",
    "GUF": "French Guiana",
    "PYF": "French Polynesia",
    "ATF": "French Southern Territories",
    "GAB": "Gabon",
    "GMB": "Gambia",
    "GEO": "Georgia",
    "DEU": "Germany",
    "GHA": "Ghana",
    "GIB": "Gibraltar",
    "GRC": "Greece",
    "GRL": "Greenland",
    "GRD": "Grenada",
    "GLP": "Guadeloupe",
    "GUM": "Guam",
    "GTM": "Guatemala",
    "GGY": "Guernsey",
    "GIN": "Guinea",
    "GNB": "Guinea-Bissau",
    "GUY": "Guyana",
    "HTI": "Haiti",
    "HMD": "Heard and Mcdonald Islands",
    "VAT": "Holy See (Vatican City State)",
    "HND": "Honduras",
    "HKG": "Hong Kong, SAR China",
    "HUN": "Hungary",
    "ISL": "Iceland",
    "IND": "India",
    "IDN": "Indonesia",
    "IRN": "Iran, Islamic Republic of",
    "IRQ": "Iraq",
    "IRL": "Ireland",
    "IMN": "Isle of Man",
    "ISR": "Israel",
    "ITA": "Italy",
    "JAM": "Jamaica",
    "JPN": "Japan",
    "JEY": "Jersey",
    "JOR": "Jordan",
    "KAZ": "Kazakhstan",
    "KEN": "Kenya",
    "KIR": "Kiribati",
    "PRK": "Korea (North)",
    "KOR": "Korea (South)",
    "KWT": "Kuwait",
    "KGZ": "Kyrgyzstan",
    "LAO": "Lao PDR",
    "LVA": "Latvia",
    "LBN": "Lebanon",
    "LSO": "Lesotho",
    "LBR": "Liberia",
    "LBY": "Libya",
    "LIE": "Liechtenstein",
    "LTU": "Lithuania",
    "LUX": "Luxembourg",
    "MAC": "Macao, SAR China",
    "MKD": "Macedonia, Republic of",
    "MDG": "Madagascar",
    "MWI": "Malawi",
    "MYS": "Malaysia",
    "MDV": "Maldives",
    "MLI": "Mali",
    "MLT": "Malta",
    "MHL": "Marshall Islands",
    "MTQ": "Martinique",
    "MRT": "Mauritania",
    "MUS": "Mauritius",
    "MYT": "Mayotte",
    "MEX": "Mexico",
    "FSM": "Micronesia, Federated States of",
    "MDA": "Moldova",
    "MCO": "Monaco",
    "MNG": "Mongolia",
    "MNE": "Montenegro",
    "MSR": "Montserrat",
    "MAR": "Morocco",
    "MOZ": "Mozambique",
    "MMR": "Myanmar",
    "NAM": "Namibia",
    "NRU": "Nauru",
    "NPL": "Nepal",
    "NLD": "Netherlands",
    "ANT": "Netherlands Antilles",
    "NCL": "New Caledonia",
    "NZL": "New Zealand",
    "NIC": "Nicaragua",
    "NER": "Niger",
    "NGA": "Nigeria",
    "NIU": "Niue",
    "NFK": "Norfolk Island",
    "MNP": "Northern Mariana Islands",
    "NOR": "Norway",
    "OMN": "Oman",
    "PAK": "Pakistan",
    "PLW": "Palau",
    "PSE": "Palestinian Territory",
    "PAN": "Panama",
    "PNG": "Papua New Guinea",
    "PRY": "Paraguay",
    "PER": "Peru",
    "PHL": "Philippines",
    "PCN": "Pitcairn",
    "POL": "Poland",
    "PRT": "Portugal",
    "PRI": "Puerto Rico",
    "QAT": "Qatar",
    "ROU": "Romania",
    "RUS": "Russian Federation",
    "RWA": "Rwanda",
    "REU": "Réunion",
    "SHN": "Saint Helena",
    "KNA": "Saint Kitts and Nevis",
    "LCA": "Saint Lucia",
    "SPM": "Saint Pierre and Miquelon",
    "VCT": "Saint Vincent and Grenadines",
    "BLM": "Saint-Barthélemy",
    "MAF": "Saint-Martin (French part)",
    "WSM": "Samoa",
    "SMR": "San Marino",
    "STP": "Sao Tome and Principe",
    "SAU": "Saudi Arabia",
    "SEN": "Senegal",
    "SRB": "Serbia",
    "SYC": "Seychelles",
    "SLE": "Sierra Leone",
    "SGP": "Singapore",
    "SVK": "Slovakia",
    "SVN": "Slovenia",
    "SLB": "Solomon Islands",
    "SOM": "Somalia",
    "ZAF": "South Africa",
    "SGS": "South Georgia and the South Sandwich Islands",
    "SSD": "South Sudan",
    "ESP": "Spain",
    "LKA": "Sri Lanka",
    "SDN": "Sudan",
    "SUR": "Suriname",
    "SJM": "Svalbard and Jan Mayen Islands",
    "SWZ": "Swaziland",
    "SWE": "Sweden",
    "CHE": "Switzerland",
    "SYR": "Syrian Arab Republic (Syria)",
    "TWN": "Taiwan, Republic of China",
    "TJK": "Tajikistan",
    "TZA": "Tanzania, United Republic of",
    "THA": "Thailand",
    "TLS": "Timor-Leste",
    "TGO": "Togo",
    "TKL": "Tokelau",
    "TON": "Tonga",
    "TTO": "Trinidad and Tobago",
    "TUN": "Tunisia",
    "TUR": "Turkey",
    "TKM": "Turkmenistan",
    "TCA": "Turks and Caicos Islands",
    "TUV": "Tuvalu",
    "UMI": "US Minor Outlying Islands",
    "UGA": "Uganda",
    "UKR": "Ukraine",
    "ARE": "United Arab Emirates",
    "GBR": "United Kingdom",
    "USA": "United States of America",
    "URY": "Uruguay",
    "UZB": "Uzbekistan",
    "VUT": "Vanuatu",
    "VEN": "Venezuela (Bolivarian Republic)",
    "VNM": "Viet Nam",
    "VIR": "Virgin Islands, US",
    "WLF": "Wallis and Futuna Islands",
    "ESH": "Western Sahara",
    "YEM": "Yemen",
    "ZMB": "Zambia",
    "ZWE": "Zimbabwe",
}

PRIMARY_COUNTRIES = {
    "DZA": "Algeria",
    "AGO": "Angola",
    "BEN": "Benin",
    "BWA": "Botswana",
    "BFA": "Burkina Faso",
    "BDI": "Burundi",
    "CPV": "Cabo Verde",
    "CMR": "Cameroon",
    "CAF": "Central African Republic",
    "TCD": "Chad",
    "COM": "Comoros",
    "CIV": "Côte d'Ivoire",
    "COD": "DR Congo",
    "DJI": "Djibouti",
    "EGY": "Egypt",
    "GNQ": "Equatorial Guinea",
    "ERI": "Eritrea",
    "SWZ": "Eswatini",
    "ETH": "Ethiopia",
    "GAB": "Gabon",
    "GHA": "Ghana",
    "GIN": "Guinea",
    "GNB": "Guinea-Bissau",
    "KEN": "Kenya",
    "LSO": "Lesotho",
    "LBR": "Liberia",
    "LBY": "Libya",
    "MDG": "Madagascar",
    "MWI": "Malawi",
    "MLI": "Mali",
    "MRT": "Mauritania",
    "MUS": "Mauritius",
    "MAR": "Morocco",
    "MOZ": "Mozambique",
    "NAM": "Namibia",
    "NER": "Niger",
    "NGA": "Nigeria",
    "RWA": "Rwanda",
    "SEN": "Senegal",
    "SYC": "Seychelles",
    "SLE": "Sierra Leone",
    "SOM": "Somalia",
    "ZAF": "South Africa",
    "SSD": "South Sudan",
    "SDN": "Sudan",
    "STP": "São Tomé and Príncipe",
    "TZA": "Tanzania",
    "GMB": "The Gambia",
    "TGO": "Togo",
    "TUN": "Tunisia",
    "UGA": "Uganda",
    "ZMB": "Zambia",
    "ZWE": "Zimbabwe",
}

DEBUNK_LANGUAGES = {
    "debunkoro": "Afaan Oromo",
    "debunkakns": "Afrikaans",
    "debunkamh": "Amharic",
    "debunkarb": "Arabic",
    "debunkbmb": "Bambara",
    "debunkeng": "English",
    "debunkfr": "French",
    "debunkful": "Fulani",
    "debunkhsa": "Hausa",
    "debunkigb": "Igbo",
    "debunkswa": "Kiswahili",
    "debunklng": "Lingala",
    "debunkpid": "Pidgin",
    "debunkses": "Sesotho",
    "debunksom": "Somali",
    "debunktig": "Tigrinya",
    "debunkwol": "Wolof",
    "debunkxho": "Xhosa",
    "debunkyor": "Yoruba",
    "debunkzu": "Zulu",
}

CONTENT_TYPES = {
    "explainer": "Explainer",
    "quickread": "Quick Read",
    "longform": "Long Form",
}

PLATFORMS = {
    "fb": "Facebook",
    "insta": "Instagram",
    "signal": "Signal",
    "telegram": "Telegram",
    "tiktok": "TikTok",
    "xtwit": "X/Twitter",
    "web": "Website",
    "whatsapp": "WhatsApp",
    "YT": "YouTube",
}

CLAIM_TOPICS = {
    "antivaxx": "Anti-vaxx",
    "arts": "Arts",
    "climate": "Climate",
    "covid": "Covid-19",
    "education": "Education",
    "elections": "Elections",
    "employment": "Employment",
    "ents": "Entertainment",
    "finance": "Finance",
    "gender": "Gender",
    "health": "Health",
    "healthmedia": "Health media",
    "LGBT": "LGBTQIA+",
    "nutrition": "Nutrition",
    "politics": "Politics",
    "religion": "Religion",
    "science": "Science",
    "sports": "Sports",
    "telecomms": "Telecommunications",
    "tourism": "Tourism",
    "transport": "Transportation",
    "wildlife": "Wildlife",
    "xenophobia": "Xenophobia",
}

GEC_CATEGORIES = {
    "african": "African countries",
    "avax": "Anti-vaxx",
    "china": "China",
    "covid19": "Covid-19",
    "eu": "EU",
    "france": "France",
    "india": "India",
    "israel": "Israel",
    "nato": "NATO",
    "nonafrican": "Non-African countries",
    "nkorea": "North Korea",
    "russia": "Russia",
    "saudi": "Saudi Arabia",
    "turkey": "Turkey",
    "uk": "UK",
    "us": "US",
}

# --- Aliases: normalised Ghost tag text -> qcode -------------------------

# Country tags, keyed onto ISO 3166-1 alpha-3 the way both country vocabularies
# are. Shared by `countries` and `countrymention1`: the qcode is the same in
# both, only the display name and the set of supported countries differ.
#
# Includes the forms the `countries` vocabulary spells oddly ("Congo,
# (Kinshasa)", "Tanzania, United Republic of"), the ones Ghost spells in French
# ("Cameroun", "Tchad"), and plain misspellings seen in the corpus.
COUNTRY_ALIASES = {
    # Côte d'Ivoire: five spellings in the corpus, none matching either label
    "ivorycoast": "CIV",
    "cotedivoire": "CIV",
    "cotedvoire": "CIV",
    "civ": "CIV",
    # DR Congo. Note the vocabularies disagree on the label, and countrymention1
    # miscoded this as COG until bootstrap_superdesk.py repaired it -- COD is
    # Kinshasa, COG is Brazzaville, and Ghost always means Kinshasa here.
    # Bare "Congo" is 197 applications and, measured over the full corpus
    # (2026-08-28), 193 of them carry no other Congo spelling -- the 4 that do
    # pair it with `drc`/`rdc`. Decisive, though: `countrymention1` has no
    # Congo-Brazzaville item at all, so as a primary country this can only be
    # Kinshasa. `countries` does have both, and this sends it to the same place
    # so the two fields cannot disagree.
    "congo": "COD",
    "democraticrepubliccongo": "COD",
    "democraticrepublicofcongo": "COD",
    "democraticrepublicofthecongo": "COD",
    "drcongo": "COD",
    "drc": "COD",
    "rdc": "COD",
    "congokinshasa": "COD",
    "congobrazzaville": "COG",
    "republicofcongo": "COG",
    # French and local spellings
    "cameroun": "CMR",
    "tchad": "TCD",
    "guineeequatoriale": "GNQ",
    "burkina": "BFA",
    # Vocabulary label drift between the two country vocabularies
    "capeverde": "CPV",
    "caboverde": "CPV",
    "eswatini": "SWZ",
    "swaziland": "SWZ",
    "thegambia": "GMB",
    "gambia": "GMB",
    "saotomeandprincipe": "STP",
    "saotomeprincipe": "STP",
    "tanzania": "TZA",
    "iran": "IRN",
    "syria": "SYR",
    "vietnam": "VNM",
    "laos": "LAO",
    "moldova": "MDA",
    "macedonia": "MKD",
    "northmacedonia": "MKD",
    "russia": "RUS",
    "unitedstates": "USA",
    "unitedstatesofamerica": "USA",
    "usa": "USA",
    "us": "USA",
    "america": "USA",
    "uk": "GBR",
    "britain": "GBR",
    "greatbritain": "GBR",
    "england": "GBR",
    "uae": "ARE",
    "dubai": "ARE",
    "abudhabi": "ARE",
    "palestine": "PSE",
    "palestinianterritories": "PSE",
    "gaza": "PSE",
    "vatican": "VAT",
    "vaticancity": "VAT",
    "holysee": "VAT",
    "southkorea": "KOR",
    "northkorea": "PRK",
    "turkiye": "TUR",
    "hongkong": "HKG",
    "taiwan": "TWN",
    "czechia": "CZE",
    "netherlandsholland": "NLD",
    "holland": "NLD",
    "ivorycost": "CIV",  # misspelling in the corpus
}

# Language tags. `language.py` maps the same tags onto an ISO 639-1 code for
# `item["language"]`, which is what Publisher routes on; this maps them onto the
# Debunklang vocabulary, which is an editorial metadata field. The two are
# independent on purpose -- see the note in pesacheck/tags.py.
DEBUNK_LANGUAGE_ALIASES = {
    "swahili": "debunkswa",
    "kiswahili": "debunkswa",
    "oromo": "debunkoro",
    "afaanoromo": "debunkoro",
    "oromiffa": "debunkoro",
    "afaanoromoo": "debunkoro",
    "amharic": "debunkamh",
    "amharigna": "debunkamh",
    "somali": "debunksom",
    "soomaali": "debunksom",
    "french": "debunkfr",
    "fench": "debunkfr",  # misspelling in the corpus, 7 applications
    "francais": "debunkfr",
    "english": "debunkeng",
    "anglais": "debunkeng",
    "tigrinya": "debunktig",
    "tigrigna": "debunktig",
    "arabic": "debunkarb",
    "hausa": "debunkhsa",
    "yoruba": "debunkyor",
    "igbo": "debunkigb",
    "pidgin": "debunkpid",
    "wolof": "debunkwol",
    "lingala": "debunklng",
    "bambara": "debunkbmb",
    "fulani": "debunkful",
    "afrikaans": "debunkakns",
    "zulu": "debunkzu",
    "xhosa": "debunkxho",
    "sesotho": "debunkses",
}

# Content-type tags. Ghost tags the corpus `Short Form` / `Long Form`; the
# vocabulary says `Quick Read` / `Explainer`. Short Form is Quick Read
# (confirmed editorially 2026-08-28), but Long Form is NOT an explainer -- it is
# its own thing, and `bootstrap_superdesk.py` adds the matching item.
CONTENT_TYPE_ALIASES = {
    "shortform": "quickread",
    "short": "quickread",
    "longform": "longform",
    "long": "longform",
    "explainer": "explainer",
}

# Platform tags. The vocabulary label "X/Twitter" normalises to "xtwitter",
# which no Ghost tag has ever been; the corpus says "Twitter".
PLATFORM_ALIASES = {
    "twitter": "xtwit",
    "x": "xtwit",
    "xtwitter": "xtwit",
    "facebook": "fb",
    "fb": "fb",
    "instagram": "insta",
    "ig": "insta",
    "whatsapp": "whatsapp",
    "youtube": "YT",
    "yt": "YT",
    "tiktok": "tiktok",
    "telegram": "telegram",
    "website": "web",
    "web": "web",
    "socialmedia": "web",
}

# Claim-topic tags. Multi-select, so a post tagged both Elections and Politics
# gets both. `Jobs` is the only real rename here; the rest are plurals and
# spelling variants of the vocabulary's own labels.
CLAIM_TOPIC_ALIASES = {
    "election": "elections",
    "elections": "elections",
    "politics": "politics",
    "political": "politics",
    "jobs": "employment",
    "job": "employment",
    "employment": "employment",
    "unemployment": "employment",
    "health": "health",
    "healthmedia": "healthmedia",
    "education": "education",
    "finance": "finance",
    "financial": "finance",
    "economy": "finance",
    "covid19": "covid",
    "covid": "covid",
    "coronavirus": "covid",
    "climate": "climate",
    "climatechange": "climate",
    "religion": "religion",
    "science": "science",
    "sport": "sports",
    "sports": "sports",
    "tourism": "tourism",
    "transport": "transport",
    "transportation": "transport",
    "wildlife": "wildlife",
    "xenophobia": "xenophobia",
    "gender": "gender",
    "nutrition": "nutrition",
    "entertainment": "ents",
    "arts": "arts",
    "telecommunications": "telecomms",
    "telecoms": "telecomms",
    "telecomms": "telecomms",
    "antivaxx": "antivaxx",
    "antivax": "antivaxx",
    "lgbt": "LGBT",
    "lgbtq": "LGBT",
    "lgbtqia": "LGBT",
}

# GEC-category tags. Written but NOT wired: `GEC` is deliberately absent from
# `pesacheck.tags.WIRED_SCHEMES` pending a look at the dry-run output, because
# it is the weakest inference in the set -- a post merely tagged `France` would
# get `GEC=france` whether or not France is what the claim is about
# (decision recorded 2026-08-28 in docs/plans/ghost-tag-field-mapping.md).
GEC_ALIASES = {
    "france": "france",
    "russia": "russia",
    "china": "china",
    "israel": "israel",
    "india": "india",
    "unitedstates": "us",
    "unitedstatesofamerica": "us",
    "usa": "us",
    "us": "us",
    "america": "us",
    "unitedkingdom": "uk",
    "uk": "uk",
    "britain": "uk",
    "turkey": "turkey",
    "turkiye": "turkey",
    "saudiarabia": "saudi",
    "saudi": "saudi",
    "northkorea": "nkorea",
    "nato": "nato",
    "eu": "eu",
    "europeanunion": "eu",
    "covid19": "covid19",
    "coronavirus": "covid19",
    "antivaxx": "avax",
    "antivax": "avax",
}

# Tags that carry no information in a corpus where every item is a fact-check.
# 1,278 applications across the full corpus, and they would otherwise all land
# in `keywords` and become public Publisher tag pages.
DROPPED_TAGS = frozenset(
    {
        "factchecking",
        "factcheck",
        "factchecks",
        "factchecked",
        "verification",
        "verified",
        "misinformation",
        "disinformation",
        "fakenews",
        "pesacheck",
    }
)
